/// <reference lib="webworker" />
import { precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { CacheFirst } from "workbox-strategies";
import { ExpirationPlugin } from "workbox-expiration";

declare let self: ServiceWorkerGlobalScope;

// Precache generated by vite-plugin-pwa
precacheAndRoute(self.__WB_MANIFEST);

// Cache audio responses (already configured in vite config; belt-and-braces)
registerRoute(
  ({ url }) => url.pathname.startsWith("/api/entries/") && url.pathname.endsWith("/audio"),
  new CacheFirst({
    cacheName: "willow-audio",
    plugins: [new ExpirationPlugin({ maxEntries: 50, maxAgeSeconds: 60 * 60 * 24 * 30 })],
  }),
);

// Push notifications
self.addEventListener("push", (event) => {
  let data: { title?: string; body?: string; url?: string } = {};
  try {
    data = event.data ? JSON.parse(event.data.text()) : {};
  } catch {
    /* malformed payload */
  }
  event.waitUntil(
    self.registration.showNotification(data.title ?? "Willow", {
      body: data.body ?? "",
      icon: "/icon-192.png",
      badge: "/favicon.png",
      data: { url: data.url ?? "/" },
    } as NotificationOptions),
  );
});

self.addEventListener("notificationclick", (event) => {
  event.notification.close();
  const url = (event.notification.data as { url?: string })?.url ?? "/";
  event.waitUntil(
    self.clients.matchAll({ type: "window", includeUncontrolled: true }).then((clients) => {
      for (const client of clients) {
        if ("focus" in client && client.url.includes(self.location.origin)) {
          return client.navigate(url).then(() => client.focus());
        }
      }
      return self.clients.openWindow(url);
    }),
  );
});
